#Create Tuple
t1=("apple","mango","cherry","kiwi","banana","orange")
print(t1)

# #Type 
t1=("apple","mango","cherry","kiwi","banana","orange")
print(type(t1))

# Length of tuple
t1=(1,2,3,4,5,6,7,8,9)
print(len(t1))

#Indexing and Slicing
t1=("apple","mango","cherry","kiwi","banana","orange")
print(t1[1])
print(t1[1:4])

# Cast value assess tuple
t1=("apple","mango","cherry","kiwi","banana","orange")
print(t1[-1])

#Convert Tuple into list
t1=("apple","mango","cherry","kiwi","banana","orange")
x=list(t1)
print(x)

#Tuple constructor
t1=tuple(("apple","mango","cherry","kiwi","banana","orange"))
print(t1)

#Add tuple item
t1=("apple","mango","cherry","kiwi","banana","orange")
x[1]="graph"
print(x)

# for Loop in tuple
t1=("apple","mango","cherry","kiwi","banana","orange")
for i in t1:
    print(i)
else:
    ("Finish")

#Tuple in while loop
t1=("apple","mango","cherry","kiwi","banana","orange")
i=0
while i== t1:
    print(i)
    i=i+1
else:
    print("Finish")

#Compare tuple
t1=(1,2,3,4,5)
t2=(6,7,8,9,10)
print(t1==t2)
print(t1<t2)
print(t1>t2)
print(t1!=t2)
